openimis/claims_android_app_java

claimManagement/src/main/java/org/openimis/imisclaims/ClaimActivity.java, claimManagement/src/main/java/org/openimis/imisclaims/EnquireActivity.java, claimManagement/src/main/java/org/openimis/imisclaims/Escape.java
Related to: https://openimis.atlassian.net/browse/OS-32
=> OS-32: Offline data files encryption in Mobile Applications

General/src/main/java/org/openimis/general/General.java, claimManagement/src/main/AndroidManifest.xml, claimManagement/src/main/java/org/openimis/imisclaims/EnquireActivity.java, claimManagement/src/main/java/org/openimis/imisclaims/Global.java, claimManagement/src/main/java/org/openimis/imisclaims/Login.java, claimManagement/src/main/java/org/openimis/imisclaims/MainActivity.java, claimManagement/src/main/java/org/openimis/imisclaims/Synchronize.java, claimManagement/src/main/java/org/openimis/imisclaims/ToRestApi.java
TASK:
https://openimis.atlassian.net/browse/OS-63
=> OS-63: Added connection to new API REST

claimManagement/src/main/java/org/openimis/imisclaims/MainActivity.java
TASK:
https://openimis.atlassian.net/browse/OS-66
=> OS-66: Checking if the user is logged in

claimManagement/src/main/java/org/openimis/imisclaims/AddItems.java, claimManagement/src/main/java/org/openimis/imisclaims/AddServices.java
TASK:
https://openimis.atlassian.net/browse/OS-67
=> OS-67: Added Option Enabled for Add Service and Item

claimManagement/build.gradle, claimManagement/src/main/AndroidManifest.xml
TASK:
https://openimis.atlassian.net/browse/OP-118
=> OP-118: Added support for Android 9

claimManagement/src/main/java/org/openimis/imisclaims/EnquireActivity.java, claimManagement/src/main/java/org/openimis/imisclaims/MainActivity.java, claimManagement/src/main/res/values/strings.xml
TICKET: [OP-291](https://openimis.atlassian.net/browse/OP-291)
=> OP-291 Claims App: Enquire doesn't work

claimManagement/src/main/java/org/openimis/imisclaims/EnquireActivity.java, claimManagement/src/main/res/layout/policylist.xml, claimManagement/src/main/res/values/strings.xml
TICKET: [OP-220](https://openimis.atlassian.net/browse/OP-220)
=> OP-220: Added missing fields for enqurity

claimManagement/src/main/AndroidManifest.xml
TICKET: [OP-283](https://openimis.atlassian.net/browse/OP-283)
=> OP-283: Exclude unnecessary permissions in manifest

claimManagement/src/main/java/org/openimis/imisclaims/EnquireActivity.java
Changes:
- Fixed HTTP photo fetching for enquire functionality
- Added support for base64 photos for enquire functionality
- Added missing error reporting
[https://openimis.atlassian.net/browse/OTC-376](https://openimis.atlassian.net/browse/OTC-376)
=> OTC-376: MV app Policy: photos are not retrived by the Enquiry function

claimManagement/build.gradle, claimManagement/src/main/java/org/openimis/imisclaims/AddItems.java, claimManagement/src/main/java/org/openimis/imisclaims/AddServices.java, claimManagement/src/main/java/org/openimis/imisclaims/SQLHandler.java
Changes:
- Added auto-filling of prices in `AddItems` and `AddServices`
- Cleaned `AddItems` and `AddServices`
- Changed url of release server to `HTTPS`
[https://openimis.atlassian.net/browse/OTC-435](https://openimis.atlassian.net/browse/OTC-435)
=> OTC-435: Add auto-filling of prices of items and services in Claims app

claimManagement/src/main/java/org/openimis/imisclaims/About.java, claimManagement/src/main/java/org/openimis/imisclaims/AddItems.java, claimManagement/src/main/java/org/openimis/imisclaims/AddServices.java, claimManagement/src/main/java/org/openimis/imisclaims/ClaimActivity.java, claimManagement/src/main/java/org/openimis/imisclaims/ClaimReview.java, claimManagement/src/main/java/org/openimis/imisclaims/Claims.java, claimManagement/src/main/java/org/openimis/imisclaims/ClaimsAdapter.java, claimManagement/src/main/java/org/openimis/imisclaims/EnquireActivity.java, claimManagement/src/main/java/org/openimis/imisclaims/Global.java, claimManagement/src/main/java/org/openimis/imisclaims/ImisActivity.java, claimManagement/src/main/java/org/openimis/imisclaims/MainActivity.java, claimManagement/src/main/java/org/openimis/imisclaims/MapItems.java, claimManagement/src/main/java/org/openimis/imisclaims/MapServices.java, claimManagement/src/main/java/org/openimis/imisclaims/Report.java, claimManagement/src/main/java/org/openimis/imisclaims/SearchClaimsActivity.java, claimManagement/src/main/java/org/openimis/imisclaims/SettingsActivity.java
Changes:
- Added language code storing and retrieving to `Global`
- Added enforcing stored language to `ImisActivity`
- Changed all remaining activities to inherit from `ImisActivity`
- Cleaned multiple classes
[https://openimis.atlassian.net/browse/OP-371](https://openimis.atlassian.net/browse/OP-371)
=> OP-371: Change language does not work in Claims app

claimManagement/src/main/java/org/openimis/imisclaims/AddItems.java, claimManagement/src/main/java/org/openimis/imisclaims/AddServices.java, claimManagement/src/main/java/org/openimis/imisclaims/ImisActivity.java, claimManagement/src/main/java/org/openimis/imisclaims/ItemAdapter.java, claimManagement/src/main/java/org/openimis/imisclaims/MainActivity.java, claimManagement/src/main/java/org/openimis/imisclaims/SQLHandler.java, claimManagement/src/main/java/org/openimis/imisclaims/ServiceAdapter.java
Changes:
- Added filtering items by input text
- Simplified `ItemAdapter` and `ServiceAdapter`
- Fixed app initialization (app will no longer cease to initialize after failed attempt)
[https://openimis.atlassian.net/browse/OP-372](https://openimis.atlassian.net/browse/OP-372)
=> OP-372: Filtering items in claim form does not work

claimManagement/src/main/java/org/openimis/imisclaims/ClaimActivity.java, claimManagement/src/main/java/org/openimis/imisclaims/DiseaseAdapter.java, claimManagement/src/main/java/org/openimis/imisclaims/MainActivity.java, claimManagement/src/main/java/org/openimis/imisclaims/MapItems.java, claimManagement/src/main/java/org/openimis/imisclaims/MapServices.java, claimManagement/src/main/java/org/openimis/imisclaims/SQLHandler.java, claimManagement/src/main/java/org/openimis/imisclaims/SynchronizeActivity.java
Changes:
- Ensured the databases are created and opened when creating `SQLHandler`
- Added additional for database checks during initialization
- Fixed some `SQLiteDatabase` and `Cursor` leaks
[https://openimis.atlassian.net/browse/OP-375](https://openimis.atlassian.net/browse/OP-375)
=> OP-375: Improved sqlite database handling

.github/workflows/main.yml, .github/workflows/manual.yml
Changes:
- Updated java version in github actions
=> Github actions Java update

.github/workflows/main.yml, .github/workflows/manual.yml
Changes:
- Changed cache from maven to gradle
=> Github actions fix

.github/workflows/main.yml, .github/workflows/manual.yml
Changes:
- Java version used in github actions updated to 11 to match project requirements
=> Java version in github worflows updated to 11

claimManagement/build.gradle, claimManagement/src/main/java/org/openimis/imisclaims/EnquireActivity.java
[https://openimis.atlassian.net/browse/OTC-498](https://openimis.atlassian.net/browse/OTC-498)
Changes:
- Updated picasso library to 2.71828
- Updated picasso library calls to adjust for API changes
=> OTC-498 Updated picasso library to 2.71828

claimManagement/build.gradle
Changes:
- Updated Release URL
=> Release URL update

claimManagement/src/main/AndroidManifest.xml
Changes:
- Removed unused permissions
=> Removed unused permissions

claimManagement/src/main/java/org/openimis/imisclaims/SynchronizeService.java
[https://openimis.atlassian.net/browse/OTC-596](https://openimis.atlassian.net/browse/OTC-596)
Changes:
- Added information about rejected claims to sync result popup
=> OTC-596: Added rejected claim information on sync

claimManagement/src/main/java/org/openimis/imisclaims/AddItems.java, claimManagement/src/main/java/org/openimis/imisclaims/AddServices.java, claimManagement/src/main/java/org/openimis/imisclaims/ClaimActivity.java, claimManagement/src/main/java/org/openimis/imisclaims/ClaimReview.java, claimManagement/src/main/java/org/openimis/imisclaims/ImisActivity.java, claimManagement/src/main/java/org/openimis/imisclaims/MainActivity.java, claimManagement/src/main/java/org/openimis/imisclaims/SQLHandler.java, claimManagement/src/main/java/org/openimis/imisclaims/SynchronizeActivity.java, claimManagement/src/main/java/org/openimis/imisclaims/SynchronizeService.java, claimManagement/src/main/java/org/openimis/imisclaims/claimlisting/ClaimListingActivity.java, claimManagement/src/main/java/org/openimis/imisclaims/claimlisting/ClaimListingFragment.java, claimManagement/src/main/java/org/openimis/imisclaims/claimlisting/ClaimListingFragmentAdapter.java, claimManagement/src/main/java/org/openimis/imisclaims/claimlisting/ClaimListingPageAdapter.java, claimManagement/src/main/res/layout/content_main.xml, claimManagement/src/main/res/values/strings.xml
[https://openimis.atlassian.net/browse/OP-802](https://openimis.atlassian.net/browse/OP-802)
[https://openimis.atlassian.net/browse/OP-803](https://openimis.atlassian.net/browse/OP-803)
Changes:
- Adjusted `ClaimActivity` and it's subactivities (`AddItems`, `AddServices`) to allow read and update and delete existing claims
- Aded READ/UPDATE interaction to claim listing items 
- Added DELETE/ARCHIVE button to claim form (Instead of NEW button when claim form if claim is loaded)
- Added `Archived` claim upload status to use when uploaded claims get archived (managing of archived claims TODO)
- Changed naming of `pending` claims to `entered`
- Added additional Android View utility methods
=> OP-802 OP-803 Implemented claim CRUD operations

claimManagement/src/main/java/org/openimis/imisclaims/EnquireActivity.java, claimManagement/src/main/java/org/openimis/imisclaims/ToRestApi.java, claimManagement/src/main/res/values/strings.xml
[https://openimis.atlassian.net/browse/OP-790](https://openimis.atlassian.net/browse/OP-790)
Changes:
- Added custom messages for common HTTP errors to translations
- Implemented custom http messages in enquire (previously all errors were reported as "member does not exists")
=> OP-790 Enquire feature issues

.gitignore, claimManagement/src/release/java/org/openimis/imisclaims/tools/Log.java
Changes:
- Added missing release Log class
- removed `release/` gitignore line
=> Fixed missing release Log class, gitignore update

claimManagement/build.gradle, claimManagement/src/main/java/org/openimis/imisclaims/EnquireActivity.java, claimManagement/src/main/java/org/openimis/imisclaims/SearchClaimsActivity.java, claimManagement/src/main/java/org/openimis/imisclaims/ToRestApi.java, claimManagement/src/main/res/values/strings.xml
[https://openimis.atlassian.net/browse/OP-940](https://openimis.atlassian.net/browse/OP-940)
Changes:
- Updated release URL
- Fixed Enquire photos
- Fixed Search Claims error messages
=> OP-940 Test mobiles apps on release server (22.10 Release)
